# -*- coding: utf-8 -*-
"""CENSOR:Defense Against Gradient Inversion via Orthogonal Subspace Bayesian Sampling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zp5REn0SiWvu-7OotNt_KH_B0PpKIJ31
"""

!pip install boto3

!pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CENSOR

import numpy as np
import torch

print("NumPy:", np.__version__)
print("Torch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())

!pip install FrEIA nevergrad

import yaml

with open("configs_biggan.yml", "r") as f:
    cfg = yaml.safe_load(f)

cfg["dataset"] = "CIFAR10"
cfg["data_path"] = "./data"

with open("configs_biggan.yml", "w") as f:
    yaml.dump(cfg, f)

print("Config patched!")

import os

file_path = "/content/CENSOR/inversefed/utils.py"

with open(file_path, "r") as f:
    content = f.read()

content = content.replace(
    "data = old_table.append(kwargs, ignore_index=True)",
    "data = pd.concat([old_table, pd.DataFrame([kwargs])], ignore_index=True)"
)

content = content.replace(
    "data = data.append(kwargs, ignore_index=True)",
    "data = pd.concat([data, pd.DataFrame([kwargs])], ignore_index=True)"
)

with open(file_path, "w") as f:
    f.write(content)

print("Patched pandas append issue!")

import yaml

with open("configs_biggan.yml", "r") as f:
    cfg = yaml.safe_load(f)

cfg["batch_size"] = 1

with open("configs_biggan.yml", "w") as f:
    yaml.dump(cfg, f)

print("Batch size reduced")

!python run_rec.py --config configs_biggan.yml

# ============================================================
# SIMPLE GRADIENT INVERSION + PSNR + SSIM + LPIPS
# ONE CELL VERSION
# ============================================================

# Install LPIPS
!pip install lpips -q

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

import matplotlib.pyplot as plt
import numpy as np

from skimage.metrics import peak_signal_noise_ratio as compare_psnr
from skimage.metrics import structural_similarity as compare_ssim

import lpips

# ============================================================
# DEVICE
# ============================================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)

# ============================================================
# LOAD CIFAR10
# ============================================================

transform = transforms.Compose([
    transforms.ToTensor()
])

dataset = torchvision.datasets.CIFAR10(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

img, label = dataset[0]

img = img.unsqueeze(0).to(device)
label = torch.tensor([label]).to(device)

# ============================================================
# SIMPLE CNN
# ============================================================

class SimpleCNN(nn.Module):

    def __init__(self):
        super().__init__()

        self.net = nn.Sequential(

            nn.Conv2d(3, 16, 3, padding=1),
            nn.ReLU(),

            nn.Conv2d(16, 32, 3, padding=1),
            nn.ReLU(),

            nn.Flatten(),

            nn.Linear(32*32*32, 10)
        )

    def forward(self, x):
        return self.net(x)

model = SimpleCNN().to(device)

# ============================================================
# COMPUTE REAL GRADIENTS
# ============================================================

criterion = nn.CrossEntropyLoss()

pred = model(img)
loss = criterion(pred, label)

real_grads = torch.autograd.grad(
    loss,
    model.parameters()
)

real_grads = [g.detach().clone() for g in real_grads]

print("Real gradients computed")

# ============================================================
# DEFENSE SWITCH
# ============================================================

USE_DEFENSE = True

if USE_DEFENSE:

    defended_grads = []

    for g in real_grads:

        noise = torch.randn_like(g) * 0.002
        defended_grads.append(g + noise)

    target_grads = defended_grads

    print("Defense Applied")

else:

    target_grads = real_grads

    print("No Defense")

# ============================================================
# INITIALIZE DUMMY IMAGE
# ============================================================

dummy_img = torch.randn_like(
    img,
    requires_grad=True,
    device=device
)

optimizer = optim.Adam([dummy_img], lr=0.1)

# ============================================================
# ATTACK LOOP
# ============================================================

iterations = 1000

print("\nStarting reconstruction...\n")

for i in range(iterations):

    optimizer.zero_grad()

    dummy_pred = model(dummy_img)

    dummy_loss = criterion(dummy_pred, label)

    dummy_grads = torch.autograd.grad(
        dummy_loss,
        model.parameters(),
        create_graph=True
    )

    grad_loss = 0

    for dg, rg in zip(dummy_grads, target_grads):

        grad_loss += ((dg - rg) ** 2).sum()

    grad_loss.backward()

    optimizer.step()

    dummy_img.data.clamp_(0,1)

    if i % 50 == 0:

        print(
            f"Iteration {i} | "
            f"Gradient Loss: {grad_loss.item():.4f}"
        )

# ============================================================
# PREPARE IMAGES
# ============================================================

original = img.detach().cpu()[0]
reconstructed = dummy_img.detach().cpu()[0]

original_np = original.permute(1,2,0).numpy()
reconstructed_np = reconstructed.permute(1,2,0).numpy()

# ============================================================
# PSNR
# ============================================================

psnr = compare_psnr(
    original_np,
    reconstructed_np,
    data_range=1.0
)

# ============================================================
# SSIM
# ============================================================

ssim = compare_ssim(
    original_np,
    reconstructed_np,
    channel_axis=2,
    data_range=1.0
)

# ============================================================
# LPIPS
# ============================================================

loss_fn = lpips.LPIPS(net='alex').to(device)

lpips_score = loss_fn(
    img,
    dummy_img
).item()

# ============================================================
# DISPLAY RESULTS
# ============================================================

fig, ax = plt.subplots(1,2, figsize=(8,4))

ax[0].imshow(original_np)
ax[0].set_title("Original")
ax[0].axis('off')

ax[1].imshow(reconstructed_np)
ax[1].set_title("Reconstructed")
ax[1].axis('off')

plt.show()

# ============================================================
# PRINT METRICS
# ============================================================

print("\n==============================")
print("RECONSTRUCTION METRICS")
print("==============================")

print(f"PSNR  : {psnr:.4f}")
print(f"SSIM  : {ssim:.4f}")
print(f"LPIPS : {lpips_score:.4f}")

print("\nDONE!")

